(import "assets/scripts/std.fe")

(= OBJF-SIZE        0)
(= OBJF-VOLUME      1)
(= OBJF-GRAVITY     2)
(= OBJF-FLOW        3)
(= OBJF-DISPERSAL   4)
(= OBJF-IS-SOLID    5)
(= OBJF-HARDNESS    6)
(= OBJF-TEXTURE     7)
(= OBJF-PHYSICS     8)

; TODO: make callbacks able to get info from calling object

(defun air-init-callback (obj-id)
  (set-obj-field OBJF-SIZE      obj-id   1)
  (set-obj-field OBJF-VOLUME    obj-id   1)
  (set-obj-field OBJF-GRAVITY   obj-id 9.8)
  (set-obj-field OBJF-FLOW      obj-id  10)
  (set-obj-field OBJF-DISPERSAL obj-id  10)
  (set-obj-field OBJF-IS-SOLID  obj-id  #f)
  (set-obj-field OBJF-HARDNESS  obj-id   0)
  (set-obj-field OBJF-TEXTURE   obj-id   0)
  (set-obj-field OBJF-PHYSICS   obj-id
	       "template-physics-callback"))

(defun grass-init-callback (obj-id)
  (set-obj-field OBJF-SIZE      obj-id   1)
  (set-obj-field OBJF-VOLUME    obj-id   1)
  (set-obj-field OBJF-GRAVITY   obj-id 9.8)
  (set-obj-field OBJF-FLOW      obj-id   0)
  (set-obj-field OBJF-DISPERSAL obj-id   5)
  (set-obj-field OBJF-IS-SOLID  obj-id  #t)
  (set-obj-field OBJF-HARDNESS  obj-id   0)
  (set-obj-field OBJF-TEXTURE   obj-id   1)
  (set-obj-field OBJF-PHYSICS   obj-id
	       "template-physics-callback"))

(defun stone-init-callback (obj-id)
  (inherit-obj-fields obj-id 1)
  (set-obj-field OBJF-FLOW      obj-id   3)
  (set-obj-field OBJF-DISPERSAL obj-id   5)
  (set-obj-field OBJF-HARDNESS  obj-id   5)
  (set-obj-field OBJF-TEXTURE   obj-id   2)
  (set-obj-field OBJF-PHYSICS   obj-id
	       "template-physics-callback"))
